---
apiVersion: v1
kind: Service
metadata:
  name: svc-fe-service-green
spec:
  type: LoadBalancer
  selector:
    app: fe-service
    deployment: green
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 22137