---
apiVersion: v1
kind: Service
metadata:
  name: svc-fe-service
  labels:
    app: fe-service
    role: green
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: fe-service
    role: green
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 22137