---
apiVersion: v1
kind: Service
metadata:
  name: svc-test-fe-service-green
  labels:
    app: fe-service
    role: test-green
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 22137
  selector:
    app: fe-service
    role: green